[package]
name = "unifree-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
anyhow = "1.0"
sha-crypt = "0.5.0"
rand = "0.9.2"
pwhash = "1.0.0"
sha2 = "0.10.9"
md5 = "0.7.0"

# Added for SSH module
tracing.workspace = true
tokio.workspace = true
iana-time-zone = "0.1.64"
rust_iso3166 = "0.1.14"
